### ISSUE TITLE
The committer has not been found in the system.

### ISSUE THREAD

**Issue by fly-shark** [apheris/cz-github-jira-conventional#2]
pip list :
![image](https://user-images.githubusercontent.com/45747286/233894086-56a553c8-b706-4100-89b2-5045fa6b2074.png)

.cz.toml config

[tool.commitizen]
name = "cz-github-jira-conventional"
version = "2.10.0"
jira_prefix = "XX-"
jira_base_url = "https://myproject.atlassian.net"
github_repo = "https://gitlabee.dd.com/dip/mp/xx"
version_files = [
    "VERSION"
]

when exec cz commit:
![image](https://user-images.githubusercontent.com/45747286/233894254-a35d66ad-1764-4447-a376-97e6c346fad1.png)

**Comment by everestas** [comment]
I am getting the same error with this warning:
```
lib/python3.9/site-packages/commitizen/cz/__init__.py:29: UserWarning: Legacy plugin 'cz_github_jira_conventional' has been ignored: please expose it the 'commitizen.plugin' entrypoint
  warnings.warn(
The committer has not been found in the system.

Try running 'pip install cz_github_jira_conventional'
```

I thought adding this to setup.py would fix it:
```
py_modules=['cz_github_jira_conventional'],
entry_points={
        'commitizen.plugin': [
            'cz_github_jira_conventional = cz_github_jira_conventional:GithubJiraConventionalCz'
        ]
    },
```
according to this documentation: https://commitizen-tools.github.io/commitizen/customization/#custom-commit-rules

**Comment by falko-apheris** [comment]
This PR should fix it, but I will have to try it first https://github.com/apheris/cz-github-jira-conventional/pull/3

Sry for my slow response.

**Comment by lavender19** [comment]
Hi @falko-apheris I am using this plugin for one of my projects and it is breaking due to the above error. Could you please let us know by when can you look into PR #3 .Thanks in advance!

**Comment by marcellovictorino** [comment]
Thanks for updating the plugin to make it compatible with newer versions of commitizen.
I tried forking and performing those exact same changes, but could not get it to work locally.
Looking forward to this release 👍

**Comment by falko-apheris** [comment]
https://pypi.org/project/cz-github-jira-conventional/ v2.0.0 is now available
