### ISSUE TITLE
Make `scope` (jira ticket) optional

### ISSUE THREAD

**Issue by marcellovictorino** [apheris/cz-github-jira-conventional#5]
I am really enjoying this solution. Thanks!
In some cases, it is necessary to perform a quick update that doe snot require version bump (style, docs etc.).
But the scope is always required.

Ideally, it would be possible to have it as optional, only generating the changelog links **IF** the user provides the scope.

**Comment by falko-apheris** [comment]
Only the following fields should cause a version bump:
- fix: pach 1.1.X
- feat: minor 1.X.0
Major versions are bumped with a breaking change.

You can read more about it here https://commitizen-tools.github.io/commitizen/bump/
