### ISSUE TITLE
Add support for any Git repo

### ISSUE THREAD

**Issue by jorgemlopez** [apheris/cz-github-jira-conventional#7]
Can you add universal support so that this plugin can be used with Bitbucket as well? Here is a fork that supports it:

https://github.com/ngoldack/cz-git-universal-jira-conventional

**Comment by hmarcuzzo** [comment]
This is still open @falko-apheris @g2010a?  

I would like to work on that issue.

**Comment by falko-apheris** [comment]
Sry I have to decline this request. I think it's totally fine to have another plugin called "universal" that does this job.
