### ISSUE TITLE
Fix import of default commit parser for commitizen 3.21.3

### ISSUE THREAD

**Issue by Kory291** [apheris/cz-github-jira-conventional#9]
In the new release 3.21.3 of commitizen the default commit parser was moved vom `commitizen/defaults.py` to `commitizen/cz/conventional_commits/conventional_commits.py`.
See the [changelog](https://github.com/commitizen-tools/commitizen/blob/master/CHANGELOG.md#v3213-2024-03-30).

**Comment by Kory291** [comment]
I just submitted a fix in #10

**Comment by ahmadgbg** [comment]
We also need this to be fixed to be able to use newer versions of Commitizen.
